package manager_test

import (
	"testing"
	"time"

	"github.com/swchck/director/manager"
)

func TestOptions_Defaults_PollInterval(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	mgr := manager.New(store, notif, reg, manager.Options{
		ServiceName: "test",
	})

	// Manager should have been created without panic.
	if mgr == nil {
		t.Fatal("New returned nil")
	}
}

func TestOptions_WithInstanceID(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	mgr := manager.New(store, notif, reg, manager.Options{ServiceName: "test"},
		manager.WithInstanceID("my-instance"),
	)

	if mgr.InstanceID() != "my-instance" {
		t.Errorf("InstanceID = %q, want 'my-instance'", mgr.InstanceID())
	}
}

func TestOptions_AutoGeneratedInstanceID(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	mgr := manager.New(store, notif, reg, manager.Options{ServiceName: "test"})

	id := mgr.InstanceID()
	if id == "" {
		t.Error("InstanceID should be auto-generated, got empty string")
	}

	// Each manager should get a unique ID.
	mgr2 := manager.New(store, notif, reg, manager.Options{ServiceName: "test"})
	if mgr2.InstanceID() == id {
		t.Error("Two managers should have different auto-generated IDs")
	}
}

func TestOptions_WithLogger(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	// Should not panic with a custom logger.
	mgr := manager.New(store, notif, reg, manager.Options{ServiceName: "test"},
		manager.WithLogger(nil), // nil logger should be handled gracefully at use-time
	)

	if mgr == nil {
		t.Fatal("New with WithLogger returned nil")
	}
}

func TestOptions_CustomPollInterval(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	// Custom options should not cause construction to fail.
	mgr := manager.New(store, notif, reg, manager.Options{
		PollInterval:             30 * time.Second,
		HeartbeatInterval:        5 * time.Second,
		WaitConfirmationsTimeout: 10 * time.Second,
		WSPollInterval:           1 * time.Minute,
		WSDebounce:               500 * time.Millisecond,
		AdvisoryLockKey:          42,
		ServiceName:              "test",
	})

	if mgr == nil {
		t.Fatal("New with custom options returned nil")
	}
}

func TestOptions_Stop_BeforeStart(t *testing.T) {
	store := newMockStorage()
	notif := newMockNotifier()
	reg := newMockRegistry()

	mgr := manager.New(store, notif, reg, manager.Options{ServiceName: "test"})

	// Stop before Start should not panic.
	mgr.Stop()
}

func TestOptions_ErrNoConfigs(t *testing.T) {
	if manager.ErrNoConfigs == nil {
		t.Error("ErrNoConfigs should not be nil")
	}

	if manager.ErrNoConfigs.Error() != "manager: no configs registered" {
		t.Errorf("ErrNoConfigs = %q", manager.ErrNoConfigs.Error())
	}
}
